name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
    tags:
    - '*'
    paths:
      # Only run test and docker publish if somde code have changed
      - 'setup.py'
      - 'setup.cfg'
      - 'pg_mvt/**'
      - 'tests/**'
      - '.pre-commit-config.yaml'
      - 'codecov.yml'
      - 'Dockerfile'
      - 'tox.ini'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install lib postgres
        run: |
          sudo apt update
          wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo apt-key add -
          echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql.list
          sudo apt update
          sudo apt-get install --yes libpq-dev postgis postgresql-14-postgis-3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install codecov pre-commit

      - name: Install module
        run: python -m pip install -e .["test"]

      - name: run pre-commit
        run: pre-commit run --all-files

      - name: Run tests
        run: python -m pytest --cov pg_mvt --cov-report xml --cov-report term-missing

      - name: Upload Results
        if: success()
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: ${{ matrix.platform }}-${{ matrix.tox-env }}
          fail_ci_if_error: false
